# Generated by Django 4.2.3 on 2024-02-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pledge_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
