# Generated by Django 4.2.3 on 2024-03-01 01:17

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_pledge_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=projects.models.default_end_date),
        ),
    ]
