# Generated by Django 4.2.3 on 2024-03-11 03:51

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=projects.models.default_start_date),
        ),
    ]
