# Generated by Django 4.2.3 on 2024-03-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
    ]
